const router = require('express').Router()
const authRoutes = require('./auth.routes')
const userRoutes = require('./user.routes')
const departmentRoutes = require('./department.routes')
const courseRoutes = require('./course.routes')
const semesterRoutes = require('./semester.routes')
const subjectRoutes = require('./subject.routes')
const studentProfileRoutes = require('./studentProfile.routes')
const facultyProfileRoutes = require('./facultyProfile.routes')
const timetableRoutes = require('./timetable.routes')
const attendanceRoutes = require('./attendance.routes')
const assignmentRoutes = require('./assignment.routes')
const submissionRoutes = require('./submission.routes')
const examinationRoutes = require('./examination.routes')
const resultRoutes = require('./result.routes')
const noticeRoutes = require('./notice.routes')
const eventRoutes = require('./event.routes')

const notificationRoutes = require('./notification.routes')
const bookRoutes = require('./book.routes')
const bookIssueRoutes = require('./bookIssue.routes')
const libraryFineRoutes = require('./libraryFine.routes')
const busRouteRoutes = require('./busRoute.routes')
const busPassRoutes = require('./busPass.routes')
const hostelRoomRoutes = require('./hostelRoom.routes')
const hostelAllocationRoutes = require('./hostelAllocation.routes')
const messMenuRoutes = require('./messMenu.routes')
const gatePassRoutes = require('./gatePass.routes')
const leaveRequestRoutes = require('./leaveRequest.routes')
const complaintRoutes = require('./complaint.routes')
const lostAndFoundRoutes = require('./lostAndFound.routes')
const canteenItemRoutes = require('./canteenItem.routes')
const canteenOrderRoutes = require('./canteenOrder.routes')
const dashboardRoutes = require('./dashboard.routes')

const auditRoutes = require('./audit.routes')
const bookmarkRoutes = require('./bookmark.routes')
const savedFilterRoutes = require('./savedFilter.routes')
const documentRoutes = require('./document.routes')
const searchRoutes = require('./search.routes')
const calendarRoutes = require('./calendar.routes')
const reportsRoutes = require('./reports.routes')
const assistantRoutes = require('./assistant.routes')

router.use('/auth', authRoutes)
router.use('/users', userRoutes)
router.use('/departments', departmentRoutes)
router.use('/courses', courseRoutes)
router.use('/semesters', semesterRoutes)
router.use('/subjects', subjectRoutes)
router.use('/student-profiles', studentProfileRoutes)
router.use('/faculty-profiles', facultyProfileRoutes)
router.use('/timetables', timetableRoutes)
router.use('/attendance', attendanceRoutes)
router.use('/assignments', assignmentRoutes)
router.use('/submissions', submissionRoutes)
router.use('/examinations', examinationRoutes)
router.use('/results', resultRoutes)
router.use('/notices', noticeRoutes)
router.use('/events', eventRoutes)
router.use('/notifications', notificationRoutes)
router.use('/books', bookRoutes)
router.use('/book-issues', bookIssueRoutes)
router.use('/library-fines', libraryFineRoutes)
router.use('/bus-routes', busRouteRoutes)
router.use('/bus-passes', busPassRoutes)
router.use('/hostel-rooms', hostelRoomRoutes)
router.use('/hostel-allocations', hostelAllocationRoutes)
router.use('/mess-menus', messMenuRoutes)
router.use('/gate-passes', gatePassRoutes)
router.use('/leave-requests', leaveRequestRoutes)
router.use('/complaints', complaintRoutes)
router.use('/lost-and-found', lostAndFoundRoutes)
router.use('/canteen-items', canteenItemRoutes)
router.use('/canteen-orders', canteenOrderRoutes)
router.use('/dashboard', dashboardRoutes)

router.use('/audit', auditRoutes)
router.use('/bookmarks', bookmarkRoutes)
router.use('/saved-filters', savedFilterRoutes)
router.use('/documents', documentRoutes)
router.use('/search', searchRoutes)
router.use('/calendar', calendarRoutes)
router.use('/reports', reportsRoutes)
router.use('/assistant', assistantRoutes)

module.exports = router
